import Image from "next/image";
import { redirect } from "next/navigation";
import type { Metadata } from "next";
import { AuthPanel } from "@/components/AuthPanel";
import { getServerUser } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Create Workspace | DealiX" };

export default async function SignUpPage() {
  if (await getServerUser()) redirect("/");
  return <main className="auth-page min-h-screen bg-[#080b13] p-3 text-zinc-100 sm:p-5 lg:p-6"><div className="auth-shell relative mx-auto grid min-h-[calc(100vh-1.5rem)] max-w-[1580px] overflow-hidden rounded-[28px] border border-white/[0.08] bg-[#0b0f19] shadow-2xl shadow-black/30 md:min-h-[calc(100vh-2.5rem)] md:grid-cols-[minmax(0,0.86fr)_minmax(420px,1fr)] lg:min-h-[calc(100vh-3rem)] lg:grid-cols-[minmax(0,1fr)_minmax(500px,0.95fr)]">
    <section className="relative hidden overflow-hidden border-r border-white/[0.07] bg-[radial-gradient(circle_at_24%_18%,rgba(57,137,255,0.20),transparent_28%),radial-gradient(circle_at_70%_72%,rgba(87,67,221,0.14),transparent_34%),linear-gradient(145deg,#111a2c_0%,#0b1120_48%,#090d16_100%)] p-8 md:flex md:flex-col md:p-10 lg:p-14"><div aria-hidden="true" className="absolute inset-0 opacity-[0.15] [background-image:linear-gradient(rgba(148,163,184,0.16)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,0.16)_1px,transparent_1px)] [background-size:42px_42px] [mask-image:linear-gradient(to_bottom,black,transparent_80%)]" /><div className="relative flex h-24 items-center"><Image src="/brand/dealix-logo-dark.svg" alt="DealiX" width={234} height={44} priority className="brand-logo-dark h-auto w-[234px] max-w-full object-contain object-left" /><Image src="/brand/dealix-logo-light.svg" alt="DealiX" width={234} height={44} priority className="brand-logo-light h-auto w-[234px] max-w-full object-contain object-left" /></div><div className="relative my-auto max-w-xl py-14"><p className="mb-5 text-xs font-semibold uppercase tracking-[0.18em] text-sky-300/80">Start with one calm workspace</p><h1 className="max-w-lg text-4xl font-medium leading-[1.08] tracking-[-0.045em] text-white lg:text-5xl">Turn every PC flip into a more informed decision.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300/85 lg:text-lg">Plan builds, manage owned parts, track profit, and use Recon to surface opportunities—all private to your account.</p></div><p className="relative text-xs text-slate-500">Your account starts with a private workspace, not shared demo data.</p></section>
    <section className="relative flex min-h-[calc(100vh-1.5rem)] items-center justify-center overflow-hidden bg-[radial-gradient(circle_at_80%_14%,rgba(57,137,255,0.10),transparent_28%),linear-gradient(145deg,#0d111c,#0a0e17)] p-5 sm:p-8 md:min-h-0 md:p-10 lg:p-14"><div aria-hidden="true" className="absolute -right-24 -top-24 h-72 w-72 rounded-full bg-sky-500/[0.08] blur-3xl" /><div className="relative w-full max-w-[470px]"><div className="mb-9 flex h-14 items-center md:hidden"><Image src="/brand/dealix-logo-dark.svg" alt="DealiX" width={224} height={42} priority className="brand-logo-dark h-auto w-[224px] max-w-full object-contain object-left" /><Image src="/brand/dealix-logo-light.svg" alt="DealiX" width={224} height={42} priority className="brand-logo-light h-auto w-[224px] max-w-full object-contain object-left" /></div><AuthPanel mode="signUp" /><p className="mt-6 text-center text-xs leading-5 text-slate-500">Your workspace stays private to your account.</p></div></section>
  </div></main>;
}
