"use client";
import type { Build } from "@/types";

export interface DealFiltersValue { category: string; compatibility: string; condition: string; marketplace: string; belowTarget: boolean; lowRisk: boolean; returnsOnly: boolean; localOnly: boolean; buildId: string; minimumProfit?: number; minimumRoi?: number; maximumBudget?: number; minimumSellerRating?: number; maximumShipping?: number; maximumRisk: string; }
export const emptyDealFilters: DealFiltersValue = { category: "All", compatibility: "All", condition: "All", marketplace: "All", belowTarget: false, lowRisk: false, returnsOnly: false, localOnly: false, buildId: "", maximumRisk: "Any" };

export function DealFilters({ value, onChange, builds, onClose }: { value: DealFiltersValue; onChange: (value: DealFiltersValue) => void; builds: Build[]; onClose?: () => void }) {
  const set = <K extends keyof DealFiltersValue>(key: K, next: DealFiltersValue[K]) => onChange({ ...value, [key]: next });
  const number = (key: "minimumProfit" | "minimumRoi" | "maximumBudget" | "minimumSellerRating" | "maximumShipping", label: string) => <label className="block text-sm text-zinc-300">{label}<input value={value[key] ?? ""} onChange={(event) => set(key, event.target.value === "" ? undefined : Number(event.target.value))} min="0" type="number" inputMode="decimal" className="mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-white/5 px-3 text-white" /></label>;
  return <aside aria-label="Advanced Recon filters" className="space-y-4 rounded-2xl border border-white/10 bg-slate-950/70 p-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Advanced filters</h2><p className="mt-1 text-xs text-zinc-500">Narrow Recon targets when needed.</p></div>{onClose ? <button onClick={onClose} className="text-sm text-sky-300">Done</button> : null}</div><label className="block text-sm text-zinc-300">Selected build<select value={value.buildId} onChange={(event) => set("buildId", event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-white/5 px-3 text-white"><option value="">Any build</option>{builds.map((build) => <option key={build.id} value={build.id}>{build.name}</option>)}</select></label><FilterSelect label="Category" value={value.category} values={["All", "Complete PC", "GPU", "CPU", "Motherboard", "RAM", "Storage", "PSU", "Cooling", "Case", "Other Parts"]} onChange={(next) => set("category", next)} /><FilterSelect label="Compatibility" value={value.compatibility} values={["All", "Compatible", "Compatible with Warning", "Unknown", "Not Compatible"]} onChange={(next) => set("compatibility", next)} /><FilterSelect label="Marketplace" value={value.marketplace} values={["All", "eBay", "Facebook Marketplace", "Mercari", "Recently Discovered", "Manual"]} onChange={(next) => set("marketplace", next)} /><FilterSelect label="Maximum risk" value={value.maximumRisk} values={["Any", "Low", "Medium", "High"]} onChange={(next) => set("maximumRisk", next)} /><div className="grid grid-cols-2 gap-3 border-t border-white/10 pt-4">{number("minimumProfit", "Min. profit")}{number("minimumRoi", "Min. ROI %")}{number("maximumBudget", "Max. landed")}{number("maximumShipping", "Max. shipping")}{number("minimumSellerRating", "Min. seller")}</div><div className="space-y-2 border-t border-white/10 pt-3 text-sm text-zinc-300"><div className="text-xs font-semibold uppercase tracking-wider text-zinc-500">Target requirements</div>{[["belowTarget", "Below target"], ["lowRisk", "Low risk"], ["returnsOnly", "Returns accepted"], ["localOnly", "Local pickup"]].map(([key, label]) => <label key={key} className="flex items-center gap-2"><input type="checkbox" checked={value[key as keyof DealFiltersValue] as boolean} onChange={(event) => set(key as keyof DealFiltersValue, event.target.checked as never)} />{label}</label>)}</div><button onClick={() => onChange(emptyDealFilters)} className="w-full rounded-xl border border-white/10 px-3 py-2 text-sm text-zinc-300">Clear all filters</button></aside>;
}
function FilterSelect({ label, value, values, onChange }: { label: string; value: string; values: string[]; onChange: (value: string) => void }) { return <label className="block text-sm text-zinc-300">{label}<select value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 min-h-11 w-full rounded-xl border border-white/10 bg-white/5 px-3 text-white">{values.map((item) => <option key={item}>{item}</option>)}</select></label>; }
