"use client";

import { useEffect, useState } from "react";
import type { Build, InventoryItem } from "@/types";

interface InventoryFormProps { builds: Build[]; initial?: InventoryItem; onSave: (item: InventoryItem) => void; onCancel: () => void; }
function blankPart(): InventoryItem { const id = `part-${crypto.randomUUID()}`; return { id, slug: id, name: "", category: "", brandModel: "", purchaseCost: 0, condition: "Good", testingStatus: "Needs Testing", currentStatus: "Available", storageLocation: "", notes: "" }; }

export function InventoryForm({ builds, initial, onSave, onCancel }: InventoryFormProps) {
  const [draft, setDraft] = useState<InventoryItem>(() => structuredClone(initial ?? blankPart())); const [dirty, setDirty] = useState(false);
  const update = <K extends keyof InventoryItem>(key: K, value: InventoryItem[K]) => { setDraft((current) => ({ ...current, [key]: value })); setDirty(true); };
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [dirty]);
  const cancel = () => { if (!dirty || window.confirm("Discard unsaved inventory changes?")) onCancel(); };
  const save = () => { if (!draft.name.trim() || !draft.brandModel.trim()) return; onSave({ ...draft, name: draft.name.trim(), slug: draft.slug === draft.id ? draft.name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || draft.id : draft.slug }); };
  return <div className="rounded-[28px] border border-white/10 bg-slate-950/60 p-6 shadow-[0_20px_60px_rgba(2,12,27,0.34)]"><div className="grid gap-3 md:grid-cols-2">{[['Part name','name'],['Category','category'],['Brand / model','brandModel'],['Condition','condition'],['Testing status','testingStatus'],['Storage location','storageLocation'],['Serial number','serialNumber'],['Seller','seller'],['Purchase date','purchaseDate'],['Warranty','warranty']].map(([label,key]) => <label key={key} className="rounded-2xl border border-white/10 bg-white/5 p-3 text-sm text-zinc-300"><span className="text-xs uppercase tracking-[0.18em] text-zinc-500">{label}</span><input value={String(draft[key as keyof InventoryItem] ?? "")} onChange={(event) => update(key as keyof InventoryItem, event.target.value as never)} className="mt-2 w-full bg-transparent text-white outline-none" /></label>)}<label className="rounded-2xl border border-white/10 bg-white/5 p-3 text-sm text-zinc-300"><span className="text-xs uppercase tracking-[0.18em] text-zinc-500">Purchase cost</span><input type="number" min="0" value={draft.purchaseCost} onChange={(event) => update("purchaseCost", Number(event.target.value))} className="mt-2 w-full bg-transparent text-white outline-none" /></label><label className="rounded-2xl border border-white/10 bg-white/5 p-3 text-sm text-zinc-300"><span className="text-xs uppercase tracking-[0.18em] text-zinc-500">Assigned build</span><select value={draft.assignedBuild ?? ""} onChange={(event) => update("assignedBuild", event.target.value || undefined)} className="mt-2 w-full bg-transparent text-white outline-none"><option value="" className="bg-slate-900">Unassigned</option>{builds.map((build) => <option key={build.id} value={build.name} className="bg-slate-900">{build.name}</option>)}</select></label></div><label className="mt-3 block rounded-2xl border border-white/10 bg-white/5 p-3 text-sm text-zinc-300"><span className="text-xs uppercase tracking-[0.18em] text-zinc-500">Notes</span><textarea value={draft.notes ?? ""} onChange={(event) => update("notes", event.target.value)} className="mt-2 min-h-24 w-full bg-transparent text-white outline-none" /></label><div className="mt-5 flex items-center gap-3"><button type="button" onClick={save} disabled={!draft.name.trim() || !draft.brandModel.trim()} className="rounded-full bg-sky-500 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">Save Part</button><button type="button" onClick={cancel} className="rounded-full border border-white/10 px-4 py-2 text-sm text-zinc-300">Cancel</button>{dirty ? <span className="text-sm text-amber-300">Unsaved changes</span> : null}</div></div>;
}
