"use client";

import { dealixStore, useDealiXData } from "@/lib/store";
import type { Build } from "@/types";

export function MarketplaceListings({ build }: { build: Build }) {
  const { listings } = useDealiXData();
  const buildListings = listings.filter((listing) => listing.buildId === build.id);
  if (!buildListings.length) return null;
  return <section className="rounded-[28px] border border-sky-400/20 bg-sky-500/10 p-6"><div><p className="text-sm font-medium text-sky-300">Marketplace Listings</p><h2 className="mt-1 text-xl font-semibold text-white">Separate active listings for {build.name}</h2></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm text-zinc-300"><thead className="text-xs uppercase tracking-[0.16em] text-zinc-500"><tr><th className="px-3 py-2">Marketplace</th><th className="px-3 py-2">Current price</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Estimated payout</th><th className="px-3 py-2">Action</th></tr></thead><tbody>{buildListings.map((listing) => { const payout = listing.price === undefined ? undefined : listing.price - (listing.estimatedFee ?? 0) - (listing.sellerShipping ?? 0); return <tr key={listing.id} className="border-t border-white/10"><td className="px-3 py-3">{listing.marketplace}</td><td className="px-3 py-3">{listing.price === undefined ? "Needs confirmation" : `$${listing.price.toFixed(2)}`}</td><td className="px-3 py-3">{listing.status}</td><td className="px-3 py-3">{payout === undefined ? "Unknown" : `$${payout.toFixed(2)}`}</td><td className="px-3 py-3"><button onClick={() => { const value = window.prompt("Enter the exact current listing price. Leave blank to keep it unknown.", listing.price?.toString() ?? ""); if (value !== null) { const price = value.trim() ? Number(value) : undefined; if (price === undefined || Number.isFinite(price)) dealixStore.updateListing({ ...listing, price, status: price === undefined ? "Needs Price Confirmation" : "Active", lastUpdated: new Date().toISOString().slice(0, 10), priceHistory: [...(listing.priceHistory ?? []), { price, date: new Date().toISOString().slice(0, 10), note: "Price updated manually" }] }); } }} className="rounded-full border border-white/10 px-3 py-1 text-xs text-sky-200">Edit listing</button></td></tr>; })}</tbody></table></div><div className="mt-4 text-sm text-amber-200">Mercari prices remain unknown until you enter the exact current value. Listings are local records, not live marketplace connections.</div></section>;
}
