"use client";

import { useState } from "react";
import { dealixStore } from "@/lib/store";
import type { InventoryItem } from "@/types";

export function PartSaleForm({ item, onClose }: { item: InventoryItem; onClose: () => void }) {
  const [sale, setSale] = useState<NonNullable<InventoryItem["partSale"]>>({ marketplace: "", payoutConfirmed: false, status: "Sold", returnStatus: "Not Returned" });
  const [message, setMessage] = useState("");
  const update = <K extends keyof typeof sale>(key: K, value: (typeof sale)[K]) => setSale((current) => ({ ...current, [key]: value }));
  const calculatedPayout = sale.payout ?? (sale.acceptedSalePrice === undefined ? undefined : sale.acceptedSalePrice - (sale.sellingFee ?? 0) - (sale.shipping ?? 0) - (sale.otherExpenses ?? 0));
  return <div className="mt-4 rounded-[28px] border border-emerald-400/20 bg-emerald-500/10 p-5"><h2 className="text-xl font-semibold text-white">Record Part Sale</h2><p className="mt-1 text-sm text-emerald-100">Enter actual payout directly, or leave it blank to calculate payout from accepted sale price minus seller expenses. Fees are never deducted twice.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{[["Marketplace", "marketplace", "text"], ["Listing price", "listingPrice", "number"], ["Accepted sale price", "acceptedSalePrice", "number"], ["Selling fee", "sellingFee", "number"], ["Seller shipping", "shipping", "number"], ["Other seller expenses", "otherExpenses", "number"], ["Actual payout", "payout", "number"], ["Sale date", "saleDate", "date"], ["Tracking number", "trackingNumber", "text"]].map(([label, key, type]) => <label key={key} className="rounded-2xl border border-white/10 bg-slate-950/40 p-3 text-sm text-zinc-300"><span className="text-xs uppercase tracking-[0.16em] text-zinc-500">{label}</span><input type={type} value={String(sale[key as keyof typeof sale] ?? "")} onChange={(event) => update(key as keyof typeof sale, type === "number" ? (event.target.value === "" ? undefined : Number(event.target.value)) as never : event.target.value as never)} className="mt-2 w-full bg-transparent text-white outline-none" /></label>)}</div><label className="mt-3 flex items-center gap-3 rounded-2xl border border-white/10 bg-slate-950/40 p-3 text-sm text-zinc-200"><input type="checkbox" checked={sale.payoutConfirmed} onChange={() => update("payoutConfirmed", !sale.payoutConfirmed)} className="h-4 w-4 accent-sky-500" />Confirm payout received</label><div className="mt-3 rounded-2xl border border-white/10 bg-slate-950/40 p-3 text-sm text-zinc-300">{sale.payoutConfirmed ? `Confirmed payout: $${(calculatedPayout ?? 0).toFixed(2)}` : "Sale recorded, payout pending."} Allocated cost: ${(item.allocatedCost ?? item.purchaseCost).toFixed(2)}</div><div className="mt-4 flex gap-3"><button onClick={() => { dealixStore.recordPartSale(item.id, { ...sale, payout: sale.payout, status: sale.payoutConfirmed ? "Paid" : "Sold" }); setMessage("Part sale saved."); }} className="rounded-full bg-sky-500 px-4 py-2 text-sm font-medium text-white">Save Sale</button><button onClick={onClose} className="rounded-full border border-white/10 px-4 py-2 text-sm text-zinc-300">Cancel</button></div>{message ? <div className="mt-3 text-sm text-emerald-200">{message}</div> : null}</div>;
}
