"use client";

import { useState } from "react";
import type { SavedDealSearch } from "@/types";

export function SavedSearchForm({ initial, onSave, onCancel }: { initial?: SavedDealSearch; onSave: (search: SavedDealSearch) => void; onCancel: () => void }) {
  const [search, setSearch] = useState<SavedDealSearch>(initial ?? { id: `saved-search-${crypto.randomUUID()}`, name: "", category: "GPU", terms: "", marketplace: "All", condition: "Used", returnsRequired: false, fulfillment: "Any", riskThreshold: "High", notificationEnabled: true, active: true, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
  const update = <K extends keyof SavedDealSearch>(key: K, value: SavedDealSearch[K]) => setSearch((current) => ({ ...current, [key]: value }));
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!search.name.trim()) return; onSave({ ...search, updatedAt: new Date().toISOString() }); };
  return <form onSubmit={submit} className="rounded-[28px] border border-sky-400/20 bg-slate-950/60 p-5"><h2 className="text-lg font-semibold text-white">Recon Watchlist</h2><p className="mt-1 text-sm text-zinc-400">Tell Recon exactly what is worth interrupting you for.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-sm text-zinc-300">Watchlist name<input required value={search.name} onChange={(event) => update("name", event.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-white/5 p-3 text-white" /></label><label className="text-sm text-zinc-300">Keywords<input value={search.terms} onChange={(event) => update("terms", event.target.value)} className="mt-1 w-full rounded-xl border border-white/5 bg-white/5 p-3 text-white" /></label><label className="text-sm text-zinc-300">Category<select value={search.category} onChange={(event) => update("category", event.target.value)} className="mt-1 w-full rounded-xl bg-slate-900 p-3 text-white">{["GPU","CPU","CPU Bundle","Motherboard","RAM","Storage","Complete PC","Other Parts"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="text-sm text-zinc-300">Maximum purchase price<input type="number" min="0" value={search.maximumItemPrice ?? ""} onChange={(event) => update("maximumItemPrice", event.target.value ? Number(event.target.value) : undefined)} className="mt-1 w-full rounded-xl bg-white/5 p-3 text-white" /></label><label className="text-sm text-zinc-300">Minimum expected profit<input type="number" min="0" value={search.minimumExpectedProfit ?? ""} onChange={(event) => update("minimumExpectedProfit", event.target.value ? Number(event.target.value) : undefined)} className="mt-1 w-full rounded-xl bg-white/5 p-3 text-white" /></label><label className="text-sm text-zinc-300">Minimum opportunity score<input type="number" min="0" max="100" value={search.minimumOpportunityScore ?? ""} onChange={(event) => update("minimumOpportunityScore", event.target.value ? Number(event.target.value) : undefined)} className="mt-1 w-full rounded-xl bg-white/5 p-3 text-white" /></label></div><div className="mt-4 flex flex-wrap gap-4 text-sm text-zinc-300"><label><input type="checkbox" checked={search.returnsRequired} onChange={(event) => update("returnsRequired", event.target.checked)} /> Returns required</label><label><input type="checkbox" checked={search.notificationEnabled} onChange={(event) => update("notificationEnabled", event.target.checked)} /> In-app alerts</label><label><input type="checkbox" checked={search.active} onChange={(event) => update("active", event.target.checked)} /> Recon active</label></div><div className="mt-4 flex gap-2"><button className="rounded-full bg-sky-500 px-4 py-2 text-sm font-semibold text-white">Save Watchlist</button><button type="button" onClick={onCancel} className="rounded-full border border-white/10 px-4 py-2 text-sm text-zinc-300">Cancel</button></div></form>;
}
