"use client";

import { useEffect, useMemo, useState } from "react";
import { DealCard } from "@/components/DealCard";
import { DealDetailDrawer } from "@/components/DealDetailDrawer";
import { DealFilters, emptyDealFilters, type DealFiltersValue } from "@/components/DealFilters";
import { SavedSearchForm } from "@/components/SavedSearchForm";
import { ReconTestPanel } from "@/components/ReconTestPanel";
import { ReconInterestCenter } from "@/components/ReconInterestCenter";
import { dealFromNormalizedListing } from "@/lib/dealDiscovery";
import type { NormalizedListing } from "@/lib/marketplaces";
import { secureRequestHeaders } from "@/lib/security/client";
import { scoreDeal } from "@/lib/dealScoring";
import { dealixStore, useDealiXData } from "@/lib/store";
import type { DealOpportunity } from "@/types";

type ReconStatus = { active: boolean; nextSweepMinutes: number; lastSweep: { startedAt?: string; listingsAnalyzed?: number; resultsFound?: number; alertsCreated?: number } | null; providers: Array<{ id: string; label: string; configured: boolean; liveSearch: boolean }> };

export default function ReconPage() {
  const data = useDealiXData(); const [selected, setSelected] = useState<DealOpportunity>(); const [filters, setFilters] = useState<DealFiltersValue>(emptyDealFilters); const [advanced, setAdvanced] = useState(false); const [watchlistsOpen, setWatchlistsOpen] = useState(false); const [status, setStatus] = useState<ReconStatus>(); const [message, setMessage] = useState("");
  useEffect(() => { let mounted = true; const refresh = async () => { try { const response = await fetch("/api/recon/status", { headers: await secureRequestHeaders(), cache: "no-store" }); const payload = await response.json() as ReconStatus; if (mounted && response.ok) setStatus(payload); } catch {} }; void refresh(); const timer = window.setInterval(refresh, 30_000); return () => { mounted = false; window.clearInterval(timer); }; }, []);
  const opportunities = useMemo(() => data.dealOpportunities.filter((deal) => !deal.dismissed && deal.sourceType !== "Mock" && passes(deal, filters) && worthwhile(deal)).sort((left, right) => { const a = scoreDeal(left); const b = scoreDeal(right); return (b.estimatedProfit ?? -Infinity) - (a.estimatedProfit ?? -Infinity) || b.score - a.score || Date.parse(right.dateFound) - Date.parse(left.dateFound); }), [data.dealOpportunities, filters]);
  const high = opportunities.filter((deal) => scoreDeal(deal).confidence === "High" && scoreDeal(deal).score >= 75).length;
  const runRecon = async () => { const profile = data.savedDealSearches.find((search) => search.active); if (!profile) { setMessage("Recon is waiting for an active monitoring profile."); return; } setMessage("Running an immediate eBay Recon sweep…"); try { const headers = await secureRequestHeaders(); const response = await fetch("/api/marketplaces/ebay/search", { method: "POST", headers, body: JSON.stringify({ queries: [profile.terms || profile.category], maxPrice: profile.maximumItemPrice, category: profile.category }) }); const payload = await response.json() as { listings?: NormalizedListing[]; error?: string }; if (!response.ok) throw new Error(payload.error); dealixStore.ingestDiscoveredDeals((payload.listings ?? []).map(dealFromNormalizedListing)); setMessage("Immediate Recon sweep complete. New targets are in the feed."); } catch (error) { setMessage(error instanceof Error ? error.message : "Recon sweep failed."); } };
  const last = status?.lastSweep?.startedAt ? relativeTime(status.lastSweep.startedAt) : "No completed sweep yet";
  return <div className="space-y-5"><header className="rounded-[28px] border border-white/10 bg-slate-950/45 p-5 shadow-[0_20px_60px_rgba(2,12,27,0.3)] sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-sky-300">Autonomous market reconnaissance</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white">DealiX Recon</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Your market monitor surfaces the best PC targets already discovered by Recon.</p></div><div className={`rounded-full border px-4 py-2 text-sm font-semibold ${status?.active ? "border-emerald-400/25 bg-emerald-500/10 text-emerald-200" : "border-amber-400/25 bg-amber-500/10 text-amber-100"}`}>{status?.active ? "● Recon Active" : "● Recon setup required"}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Last sweep" value={last} /><Metric label="Next sweep" value={status?.active ? `${status.nextSweepMinutes} minutes` : "After setup"} /><Metric label="Listings analyzed" value={String(status?.lastSweep?.listingsAnalyzed ?? 0)} /><Metric label="New targets" value={String(status?.lastSweep?.resultsFound ?? 0)} /><Metric label="High confidence" value={String(high)} /></div><div className="mt-4 flex flex-wrap gap-2 text-xs">{status?.providers?.map((provider) => <span key={provider.id} className={`rounded-full border px-3 py-1.5 ${provider.configured && provider.liveSearch ? "border-emerald-400/20 bg-emerald-500/10 text-emerald-200" : "border-white/10 bg-white/[0.03] text-zinc-500"}`}>{provider.configured && provider.liveSearch ? "✓" : "○"} {provider.label}{!provider.liveSearch ? " · planned" : ""}</span>)}</div></header>
    {message ? <p role="status" className="rounded-xl border border-sky-400/20 bg-sky-500/10 px-4 py-3 text-sm text-sky-100">🎯 {message}</p> : null}
    <ReconTestPanel />
    <ReconInterestCenter />
    <section className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-sky-300">Recon Activity</p><div className="mt-3 space-y-2">{data.notifications.filter((item) => !item.dismissed && /target|recon/i.test(`${item.title} ${item.description}`)).slice(0, 5).map((item) => <div key={item.id} className="flex items-start justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.025] px-3 py-2"><div><p className="text-sm font-medium text-white">{item.title}</p><p className="mt-0.5 text-xs text-zinc-400">{item.description}</p></div><button onClick={() => dealixStore.dismissNotification(item.id)} className="text-xs text-zinc-500 hover:text-zinc-200">Dismiss</button></div>)}{!data.notifications.some((item) => !item.dismissed && /target|recon/i.test(`${item.title} ${item.description}`)) ? <p className="text-sm text-zinc-500">Recon is watching your interests. Activity appears when a worthwhile target is acquired.</p> : null}</div></section>
    <section className="rounded-2xl border border-white/10 bg-slate-950/35 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-sky-300">Recon Watchlists</p><p className="mt-1 text-sm text-zinc-400">{data.savedDealSearches.filter((item) => item.active).length} active profiles are monitoring the market for you.</p></div><button onClick={() => setWatchlistsOpen(!watchlistsOpen)} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-zinc-200">{watchlistsOpen ? "Hide watchlists" : "Manage watchlists"}</button></div>{watchlistsOpen ? <div className="mt-4 space-y-3"><div className="grid gap-2 md:grid-cols-2">{data.savedDealSearches.map((item) => <div key={item.id} className="rounded-xl border border-white/10 bg-white/[0.025] px-3 py-2 text-sm"><span className="font-medium text-white">{item.name}</span><span className="ml-2 text-xs text-zinc-500">{item.active ? "Monitoring" : "Paused"}</span></div>)}</div><SavedSearchForm onSave={(watchlist) => { dealixStore.saveSearch(watchlist); setWatchlistsOpen(false); setMessage(`${watchlist.name} is now being monitored.`); }} onCancel={() => setWatchlistsOpen(false)} /></div> : null}</section>
    <section><div className="mb-4 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-emerald-300">New targets acquired</p><h2 className="mt-1 text-xl font-semibold text-white">Highest-value opportunities</h2><p className="mt-1 text-sm text-zinc-500">Ranked by estimated profit, opportunity score, then discovery time.</p></div><div className="flex gap-2"><button onClick={() => setAdvanced(!advanced)} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-zinc-300">Advanced filters</button><button onClick={runRecon} className="rounded-xl bg-sky-500 px-3 py-2 text-sm font-medium text-white hover:bg-sky-400">Run Recon</button></div></div>{advanced ? <div className="mb-4"><DealFilters value={filters} onChange={setFilters} builds={data.builds} onClose={() => setAdvanced(false)} /></div> : null}<div className="space-y-3">{opportunities.length ? opportunities.map((deal) => <DealCard key={deal.id} deal={deal} onSelect={() => setSelected(deal)} />) : <div className="rounded-2xl border border-dashed border-white/15 p-10 text-center"><h2 className="font-semibold text-white">No profitable targets found.</h2><p className="mt-2 text-sm text-zinc-400">Recon is still sweeping enabled marketplaces. You&apos;ll be notified when a new opportunity is detected.</p></div>}</div></section>{selected ? <DealDetailDrawer deal={selected} onClose={() => setSelected(undefined)} /> : null}</div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.035] px-4 py-3"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-zinc-500">{label}</p><p className="mt-1 truncate text-sm font-semibold text-white">{value}</p></div>; }
function relativeTime(value: string) { const minutes = Math.max(0, Math.round((Date.now() - Date.parse(value)) / 60_000)); return minutes < 1 ? "Just now" : `${minutes} min ago`; }
function passes(deal: DealOpportunity, filters: DealFiltersValue) { const score = scoreDeal(deal); return (filters.category === "All" || deal.category === filters.category) && (filters.compatibility === "All" || score.compatibility === filters.compatibility) && (filters.marketplace === "All" || deal.marketplace === filters.marketplace) && (filters.minimumProfit === undefined || (score.estimatedProfit ?? -Infinity) >= filters.minimumProfit) && (filters.minimumRoi === undefined || (score.estimatedRoi ?? -Infinity) >= filters.minimumRoi) && (filters.maximumRisk === "Any" || score.risk === filters.maximumRisk); }
function worthwhile(deal: DealOpportunity) { const score = scoreDeal(deal); return score.score >= 55 && score.confidence !== "Low" && score.confidence !== "Insufficient Data" && score.risk !== "Critical" && (score.estimatedProfit ?? -1) > 0 && (score.estimatedRoi ?? -1) > 0 && score.compatibility !== "Not Compatible"; }
