import { NextRequest, NextResponse } from "next/server";
import type { SupabaseClient } from "@supabase/supabase-js";
import { processReconListings } from "@/lib/recon/pipeline";
import { createSupabaseAdminClient } from "@/lib/supabase/server";
import { assertSameOrigin, requireUser } from "@/lib/security/request";
import { enforceRateLimit } from "@/lib/security/rateLimit";
import type { NormalizedListing } from "@/lib/marketplaces";
import type { SavedDealSearch } from "@/types";

const enabled = () => process.env.NODE_ENV === "development" || process.env.NEXT_PUBLIC_RECON_TEST_MODE === "true";
export async function POST(request: NextRequest) { try { assertSameOrigin(request); if (!enabled()) return NextResponse.json({ error: "Not found" }, { status: 404 }); if (!process.env.SUPABASE_SERVICE_ROLE_KEY) return NextResponse.json({ error: "Recon Test Mode needs the server-only SUPABASE_SERVICE_ROLE_KEY." }, { status: 503 }); const user = await requireUser(request); await enforceRateLimit("recon-test", user.id, 20, 60_000); const body = await request.json() as { count?: number; quality?: "high" | "low" }; const count = Math.min(Math.max(Number(body.count) || 10, 1), 50); const client = createSupabaseAdminClient() as unknown as SupabaseClient; const { data, error: profileError } = await client.from("saved_searches").select("data").eq("user_id", user.id); if (profileError) throw profileError; const profiles = (data ?? []).map((row) => row.data).filter((item): item is SavedDealSearch => Boolean(item && typeof item === "object" && (item as SavedDealSearch).active)); if (!profiles.length) return NextResponse.json({ error: "Create and save at least one active Recon Watchlist before testing." }, { status: 422 }); const result = await processReconListings(client, user.id, profiles, fixtures(count, body.quality ?? "high")); return NextResponse.json({ ...result, generated: count }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { if (error instanceof Response) return error; const detail = error instanceof Error ? error.message : "Unknown error"; return NextResponse.json({ error: process.env.NODE_ENV === "development" ? `Test Recon failed: ${detail}` : "Test Recon failed." }, { status: 400 }); } }
function fixtures(count: number, quality: "high" | "low"): NormalizedListing[] { const models = ["RTX 4070", "RTX 4080", "RTX 3080", "Ryzen 7800X3D", "Ryzen 5 5600", "AM5 B650 Motherboard", "Gaming PC"]; return Array.from({ length: count }, (_, index) => { const model = models[index % models.length]; const high = quality === "high"; const price = high ? 350 + (index % 4) * 25 : 850 + index * 10; return { providerId: "recon-test" as NormalizedListing["providerId"], externalId: `test-${quality}-${Date.now()}-${index}`, title: model, marketplace: "Recon Test Provider", url: `https://example.invalid/recon-test/${index}`, price, shipping: high ? 15 : 55, condition: high ? "Used" : "For parts or not working", seller: { name: high ? "Verified test seller" : "Low quality test seller", rating: high ? 4.9 : 2.1 }, returnPolicy: high ? "Returns accepted for 30 days" : "Returns not accepted", category: model.includes("Ryzen") ? "CPU" : model.includes("Motherboard") ? "Motherboard" : model.includes("PC") ? "Complete PC" : "GPU", images: [], foundAt: new Date().toISOString() }; }); }
