'use client';

import Link from "next/link";
import { useMemo, useState } from "react";
import { dealixStore } from "@/lib/store";
import { useBuildLabDraft, type BuildLabSelection, type BuildLabSlot } from "@/components/BuildLabDraft";

const rows = [["CPU", "Choose CPU"], ["CPU Cooler", "Choose Cooler"], ["Motherboard", "Choose Motherboard"], ["RAM", "Choose Memory"], ["GPU", "Choose Graphics Card"], ["Storage", "Choose Storage"], ["Case", "Choose Case"], ["PSU", "Choose PSU"], ["Operating System", "Choose Operating System"], ["Accessories", "Choose Accessories"]] as const;
type Slot = BuildLabSlot;
type Selection = BuildLabSelection;
const required: Slot[] = ["CPU", "CPU Cooler", "Motherboard", "RAM", "GPU", "Storage", "Case", "PSU"];
const money = (value?: number) => value === undefined ? "Not recorded" : `$${value.toFixed(2)}`;

export default function BuildLabPage() {
  const [name, setName] = useState("Untitled flip build");
  const { selected, setSelected } = useBuildLabDraft();
  const [notice, setNotice] = useState("");
  const current = selected;

  const compatibility = useMemo(() => evaluateCompatibility(current), [current]);
  const totalCost = Object.values(current).reduce((sum, item) => sum + (item?.cost ?? 0), 0);
  const values = Object.values(current).filter((item) => item?.value !== undefined) as Selection[];
  const totalValue = values.reduce((sum, item) => sum + (item.value ?? 0), 0);
  const allValueKnown = values.length === Object.keys(current).length && values.length > 0;
  const profit = allValueKnown ? totalValue - totalCost : undefined;
  const roi = profit === undefined || totalCost <= 0 ? undefined : (profit / totalCost) * 100;
  const watts = Object.values(current).reduce((sum, item) => sum + (item?.specs?.tdpWatts ?? 0), 0);
  const missing = required.filter((slot) => !current[slot]);
  const save = () => { const id = `planner-${crypto.randomUUID()}`; dealixStore.addBuild({ id, slug: `${name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "build"}-${id.slice(-6)}`, name: name.trim() || "Untitled flip build", status: "Active", buildCost: totalCost, cpu: current.CPU?.name, cooling: current["CPU Cooler"]?.name, motherboard: current.Motherboard?.name, ram: current.RAM?.name, gpu: current.GPU?.name, storage: current.Storage?.name, case: current.Case?.name, psu: current.PSU?.name, os: current["Operating System"]?.name, accessories: current.Accessories?.name, estimatedResale: allValueKnown ? `$${totalValue.toFixed(2)}` : undefined, projectedProfit: profit === undefined ? undefined : `$${profit.toFixed(2)}`, partsNeeded: missing.map((part) => ({ name: part, priority: "High", status: "Needed", details: "Select a compatible component before finalizing." })), health: compatibility.blocked ? "Blocked" : compatibility.issues.length ? "Needs attention" : "Not assessed", notes: "Created in Build Lab. Costs and values reflect only selected parts with recorded data." }); setNotice("Build saved. You can manage it from Builds."); };

  return <main className="space-y-6 pb-8">
    <header className="rounded-[28px] border border-white/10 bg-slate-950/50 p-6 shadow-[0_24px_80px_rgba(2,12,27,.32)] sm:p-8"><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-sky-300">DealiX Build Lab</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-white sm:text-4xl">Build list</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Choose verified components one category at a time. DealiX uses your inventory, saved Recon targets, and its specification catalog—never default parts.</p></div><div className="flex flex-wrap gap-2"><Link href="/builds" className="rounded-xl border border-white/10 px-4 py-2.5 text-sm text-zinc-300 hover:bg-white/5">Manage builds</Link><button onClick={save} className="rounded-xl bg-sky-500 px-4 py-2.5 text-sm font-medium text-white transition hover:-translate-y-0.5 hover:bg-sky-400">Save build</button></div></div></header>
    <section className={`rounded-[24px] border p-4 ${compatibility.blocked ? "border-rose-400/25 bg-rose-500/[.07]" : compatibility.issues.length ? "border-amber-400/25 bg-amber-500/[.07]" : "border-emerald-400/25 bg-emerald-500/[.07]"}`}><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-medium text-white">{compatibility.blocked ? "Compatibility conflict" : compatibility.issues.length ? "Compatibility needs review" : "Compatibility has no known conflicts"}</p><p className="mt-1 text-sm text-zinc-400">{compatibility.issues[0] ?? "Add components to run socket, memory, fit, and power checks."}</p></div><div className="text-right"><p className="text-xs uppercase tracking-[.14em] text-zinc-500">Component draw</p><p className="mt-1 text-lg font-semibold text-white">{watts ? `${watts}W` : "Not calculated"}</p></div></div></section>
    <section className="rounded-[24px] border border-white/10 bg-slate-950/35 p-4"><label className="block text-xs font-semibold uppercase tracking-[.14em] text-zinc-500">Build name<input value={name} onChange={(event) => setName(event.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-white/[.04] px-3 py-2.5 text-base text-white outline-none focus:border-sky-400/50" /></label></section>
    <section className="overflow-hidden rounded-[28px] border border-white/10 bg-slate-950/40 shadow-[0_20px_60px_rgba(2,12,27,.3)]"><div className="grid grid-cols-[minmax(115px,.5fr)_minmax(0,1.8fr)_auto] gap-4 border-b border-white/10 px-5 py-3 text-xs font-semibold uppercase tracking-[.13em] text-zinc-500"><span>Component</span><span>Selection</span><span>Actions</span></div>{rows.map(([slot, action]) => { const item = current[slot]; return <div key={slot} className="grid grid-cols-[minmax(115px,.5fr)_minmax(0,1.8fr)_auto] gap-4 border-b border-white/[.07] px-5 py-5 last:border-0"><div className="font-medium text-sky-200">{slot}</div><div>{item ? <><p className="font-medium text-white">{item.name}</p><p className="mt-1 text-xs text-zinc-500"><span className="rounded-full border border-white/10 px-2 py-0.5">{item.source}</span> <span className="ml-1">{item.note}</span>{item.cost !== undefined ? ` · ${money(item.cost)}` : ""}</p></> : <p className="text-sm text-zinc-500">No component selected</p>}</div><div className="flex flex-wrap justify-end gap-2"><Link href={`/planner/browse?slot=${encodeURIComponent(slot)}`} className="rounded-xl bg-sky-500 px-3 py-2 text-sm font-medium text-white hover:bg-sky-400">{item ? "Replace" : action}</Link>{item ? <button onClick={() => { setSelected((previous) => ({ ...previous, [slot]: undefined })); window.history.replaceState(null, "", "/planner"); }} className="rounded-xl border border-white/10 px-3 py-2 text-sm text-zinc-300 hover:bg-white/5">Remove</button> : null}</div></div>; })}</section>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric label="Current cost" value={money(totalCost)} note="Recorded purchase prices only" /><Metric label="Market value" value={allValueKnown ? money(totalValue) : "Needs value data"} note="Selected parts with entered values" /><Metric label="Estimated profit" value={money(profit)} note="Value minus selected cost" /><Metric label="ROI" value={roi === undefined ? "Needs cost and value" : `${roi.toFixed(1)}%`} note={`${required.length - missing.length}/${required.length} core parts selected`} /></section>
    {notice ? <p role="status" className="rounded-xl border border-emerald-400/20 bg-emerald-500/10 p-3 text-sm text-emerald-100">{notice}</p> : null}
  </main>;
}

function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="rounded-[22px] border border-white/10 bg-white/[.035] p-5"><p className="text-xs uppercase tracking-[.14em] text-zinc-500">{label}</p><p className="mt-2 text-xl font-semibold text-white">{value}</p><p className="mt-1 text-xs text-zinc-500">{note}</p></div>; }
function evaluateCompatibility(selected: Partial<Record<Slot, Selection>>) { const issues: string[] = []; const cpu = selected.CPU?.specs; const board = selected.Motherboard?.specs; const ram = selected.RAM?.specs; const gpu = selected.GPU?.specs; const psu = selected.PSU?.specs; const pcCase = selected.Case?.specs; const cooler = selected["CPU Cooler"]?.specs; if (cpu?.socket && board?.socket && cpu.socket !== board.socket) issues.push(`CPU socket ${cpu.socket} does not match motherboard socket ${board.socket}.`); if (board?.ramGeneration && ram?.ramGeneration && board.ramGeneration !== ram.ramGeneration) issues.push(`Motherboard requires ${board.ramGeneration}; selected memory is ${ram.ramGeneration}.`); if (board?.formFactor && pcCase?.supportedFormFactors && !pcCase.supportedFormFactors.includes(board.formFactor)) issues.push(`The case does not support the ${board.formFactor} motherboard.`); if (gpu?.gpuLengthMm && pcCase?.maxGpuLengthMm && gpu.gpuLengthMm > pcCase.maxGpuLengthMm) issues.push(`GPU length exceeds the case clearance.`); if (cooler?.coolerHeightMm && pcCase?.maxCoolerHeightMm && cooler.coolerHeightMm > pcCase.maxCoolerHeightMm) issues.push(`Cooler height exceeds the case clearance.`); const draw = (cpu?.tdpWatts ?? 0) + (gpu?.tdpWatts ?? 0); if (draw && psu?.wattage && psu.wattage < draw + 120) issues.push(`PSU wattage may not leave sufficient headroom for the selected CPU and GPU.`); return { issues, blocked: issues.some((issue) => /does not match|does not support|exceeds/.test(issue)) }; }
