import type { AiMessage, Build, Deal, DealOpportunity, InventoryItem, MarketplaceListing, NotificationItem, SavedDealSearch, TaskItem, TestingChecklistItem } from "@/types";

export const navItems = [
  { href: "/", label: "Dashboard" },
  { href: "/builds", label: "Builds" },
  { href: "/inventory", label: "Inventory" },
  { href: "/deals", label: "Market Intelligence" },
  { href: "/planner", label: "AI Build Planner" },
  { href: "/sales", label: "Sales" },
  { href: "/analytics", label: "Analytics" },
  { href: "/ai", label: "AI Assistant" },
  { href: "/settings", label: "Settings" },
];

export const dashboardStats = {
  confirmedNetProfit: 244.73,
  completedSales: 1,
  activeBuilds: 2,
  totalRecordedBuildCost: 1695.0,
};

export const builds: Build[] = [
  {
    id: "build-1",
    slug: "i5-12600k-rtx-4060",
    name: "i5-12600K + RTX 4060 Gaming PC",
    status: "Sold",
    buildCost: 614.5,
    salePrice: 997.5,
    mercariPayout: 859.23,
    netProfit: 244.73,
    cpu: "Intel Core i5-12600K",
    gpu: "MSI RTX 4060 Ventus 2X OC 8GB",
    ram: "32GB DDR4",
    storage: "500GB SSD + 3TB HDD",
    psu: "Corsair RM750 750W 80+ Gold",
    os: "Windows 11 activated",
    windowsActivation: "Activated",
    accessories: "USB Wi-Fi adapter, extra fan, RGB controller",
    workCompleted: ["cleaned", "upgraded", "cable managed", "stress tested"],
    startDate: "2026-06-01",
    completionDate: "2026-07-10",
    listingDate: "2026-07-12",
    saleDate: "2026-07-24",
    lastUpdated: "2026-07-24",
    notes: "Cleaned, upgraded, cable managed, and stress tested.",
    parts: [
      { name: "Intel Core i5-12600K", type: "CPU", condition: "Excellent", serialNumber: "CPU-12600K-01", purchasePrice: 249, seller: "Micro Center", purchaseDate: "2025-03-01", warranty: "No warranty", assignedBuild: "i5-12600K + RTX 4060 Gaming PC", currentLocation: "Desk", notes: "No issues observed." },
      { name: "MSI RTX 4060 Ventus 2X OC 8GB", type: "GPU", condition: "Good", serialNumber: "GPU-4060-01", purchasePrice: 199, seller: "eBay", purchaseDate: "2025-03-02", warranty: "30-day seller warranty", assignedBuild: "i5-12600K + RTX 4060 Gaming PC", currentLocation: "Build station", notes: "Tested and passing." },
    ],
    timeline: [
      { label: "Purchased", completed: true, date: "2025-03-01" },
      { label: "Cleaned", completed: true, date: "2025-03-12" },
      { label: "Built", completed: true, date: "2025-03-13" },
      { label: "Stress tested", completed: true, date: "2025-03-14" },
      { label: "Benchmarked", completed: true, date: "2025-03-14" },
      { label: "Photographed", completed: true, date: "2025-03-15" },
      { label: "Listed", completed: true, date: "2025-03-16" },
      { label: "Sold", completed: true, date: "2025-03-22" },
      { label: "Delivered", completed: true, date: "2025-03-24" },
    ],
    photos: { mainPhoto: "Placeholder", insideCase: "Placeholder", gpu: "Placeholder", cableManagement: "Placeholder", benchmarkScreenshot: "Placeholder", windowsScreenshot: "Placeholder" },
    benchmarking: { cinebench: "Not entered", threeDMark: "Not entered", crystalDiskMark: "Not entered", cpuIdleTemp: "35°C", cpuLoadTemp: "72°C", gpuIdleTemp: "35°C", gpuLoadTemp: "73°C", status: "Pass", notes: "Benchmarking notes pending." },
    profitBreakdown: { salePrice: 997.5, marketplaceFees: 99.75, shipping: 38.52, taxes: 0, buildCost: 614.5, payout: 859.23, netProfit: 244.73, roi: "39.83%", profitMargin: "24.53%", marketplace: "Mercari", acceptedOffer: "Yes", listingPrice: 999 },
  },
  {
    id: "build-2",
    slug: "legacy-powerhouse",
    name: "Legacy Powerhouse",
    status: "Active",
    buildCost: 365.5,
    estimatedResale: "550-599",
    projectedProfit: "134.5-204.5",
    cpu: "Intel Core i7-7700K",
    gpu: "GTX 1080",
    ram: "16GB DDR4",
    storage: "1.36TB",
    psu: "500W",
    motherboard: "Not entered",
    cooling: "3 Corsair RGB fans",
    os: "Windows 10",
    windowsActivation: "Not entered",
    accessories: "USB hub, extra SATA cable",
    workCompleted: ["cleaned", "upgraded"],
    partsNeeded: [
      {
        name: "Compatible Motherboard",
        priority: "High",
        status: "Searching",
        details: "Needs a motherboard compatible with the Intel Core i7-7700K and DDR4 memory.",
      },
    ],
    startDate: "2025-04-10",
    completionDate: "Not entered",
    listingDate: "Not entered",
    saleDate: "Not entered",
    lastUpdated: "2025-04-15",
    notes: "Blocked waiting for a compatible motherboard and final testing.",
    parts: [
      { name: "Intel Core i7-7700K", type: "CPU", condition: "Good", serialNumber: "CPU-7700K-01", purchasePrice: 115, seller: "Local seller", purchaseDate: "2025-04-01", warranty: "No warranty", assignedBuild: "Legacy Powerhouse", currentLocation: "Build station", notes: "Needs new board." },
      { name: "GTX 1080", type: "GPU", condition: "Good", serialNumber: "GPU-1080-01", purchasePrice: 85, seller: "Marketplace", purchaseDate: "2025-04-03", warranty: "No warranty", assignedBuild: "Legacy Powerhouse", currentLocation: "Storage", notes: "Still needs testing." },
    ],
    timeline: [
      { label: "Purchased", completed: true, date: "2025-04-01" },
      { label: "Cleaned", completed: true, date: "2025-04-10" },
      { label: "Upgraded", completed: true, date: "2025-04-12" },
      { label: "Built", completed: false },
      { label: "Stress tested", completed: false },
      { label: "Benchmarked", completed: false },
      { label: "Photographed", completed: false },
      { label: "Listed", completed: false },
      { label: "Sold", completed: false },
      { label: "Delivered", completed: false },
    ],
    photos: { mainPhoto: "Placeholder", insideCase: "Placeholder", gpu: "Placeholder", cableManagement: "Placeholder", benchmarkScreenshot: "Placeholder", windowsScreenshot: "Placeholder" },
    benchmarking: { cinebench: "Not entered", threeDMark: "Not entered", crystalDiskMark: "Not entered", cpuIdleTemp: "Not entered", cpuLoadTemp: "Not entered", gpuIdleTemp: "Not entered", gpuLoadTemp: "Not entered", status: "Not entered", notes: "Testing blocked until motherboard arrives." },
    profitBreakdown: { salePrice: 0, marketplaceFees: 0, shipping: 0, taxes: 0, buildCost: 365.5, payout: 0, netProfit: 0, roi: "Not entered", profitMargin: "Not entered", marketplace: "Not entered", acceptedOffer: "Not entered", listingPrice: 0 },
  },
  {
    id: "build-3",
    slug: "blue-titan",
    name: "Blue Titan",
    status: "Listed",
    buildCost: 715.0,
    listingPrice: 999.0,
    expectedSale: "925-975",
    projectedProfit: "210-260",
    cpu: "AMD Ryzen 5 5500",
    gpu: "ASUS RTX 3060 Ti 8GB",
    ram: "16GB DDR4",
    storage: "500GB Samsung EVO SSD + 2TB NVMe",
    motherboard: "Gigabyte B550M K",
    psu: "650W",
    case: "Montech XR Black",
    cooling: "4 blue RGB fans",
    os: "Windows 11 Pro activated",
    windowsActivation: "Activated",
    accessories: "RGB controller, spare cable kit",
    workCompleted: ["cleaned", "upgraded", "cable managed", "stress tested"],
    startDate: "2025-02-20",
    completionDate: "2025-02-24",
    listingDate: "2025-02-28",
    saleDate: "Not entered",
    lastUpdated: "2025-03-01",
    notes: "Listed and waiting for the right buyer.",
    parts: [
      { name: "Ryzen 5 5500", type: "CPU", condition: "Excellent", serialNumber: "CPU-5500-01", purchasePrice: 120, seller: "Best Buy", purchaseDate: "2025-02-18", warranty: "No warranty", assignedBuild: "Blue Titan", currentLocation: "Build station", notes: "Works well." },
      { name: "ASUS RTX 3060 Ti 8GB", type: "GPU", condition: "Good", serialNumber: "GPU-3060TI-01", purchasePrice: 270, seller: "eBay", purchaseDate: "2025-02-19", warranty: "30-day seller warranty", assignedBuild: "Blue Titan", currentLocation: "Desk", notes: "Has been tested." },
    ],
    timeline: [
      { label: "Purchased", completed: true, date: "2025-02-18" },
      { label: "Cleaned", completed: true, date: "2025-02-20" },
      { label: "Built", completed: true, date: "2025-02-24" },
      { label: "Stress tested", completed: true, date: "2025-02-25" },
      { label: "Benchmarked", completed: true, date: "2025-02-25" },
      { label: "Photographed", completed: true, date: "2025-02-27" },
      { label: "Listed", completed: true, date: "2025-02-28" },
      { label: "Sold", completed: false },
      { label: "Delivered", completed: false },
    ],
    photos: { mainPhoto: "Placeholder", insideCase: "Placeholder", gpu: "Placeholder", cableManagement: "Placeholder", benchmarkScreenshot: "Placeholder", windowsScreenshot: "Placeholder" },
    benchmarking: { cinebench: "Not entered", threeDMark: "Not entered", crystalDiskMark: "Not entered", cpuIdleTemp: "38°C", cpuLoadTemp: "79°C", gpuIdleTemp: "36°C", gpuLoadTemp: "76°C", status: "Pass", notes: "Stable under light load." },
    profitBreakdown: { salePrice: 0, marketplaceFees: 0, shipping: 0, taxes: 0, buildCost: 715, payout: 0, netProfit: 0, roi: "Not entered", profitMargin: "Not entered", marketplace: "Mercari", acceptedOffer: "Not entered", listingPrice: 999 },
  },
];

export const inventoryItems: InventoryItem[] = [
  {
    id: "part-1",
    name: "RTX 3070 Founders Edition",
    category: "GPU",
    brandModel: "NVIDIA RTX 3070 FE",
    purchaseCost: 224.0,
    condition: "Good",
    testingStatus: "Needs Testing",
    currentStatus: "Installed in Personal PC",
    availability: "Unavailable",
    personalPc: true,
    storageLocation: "Installed in Main PC",
    slug: "rtx-3070-founders-edition",
    locationNote: "Current location confirmed: Main PC. This asset is not available for DealiX builds.",
    assetHistory: [{ action: "Purchased", note: "Acquired for GPU swap." }, { action: "Installed in Main PC", note: "Current location confirmed." }],
  },
  {
    id: "part-2",
    name: "Corsair RM750 power supply",
    category: "PSU",
    brandModel: "Corsair RM750",
    purchaseCost: 89.0,
    condition: "Excellent",
    testingStatus: "Passed",
    currentStatus: "Available",
    storageLocation: "Parts bin A",
    slug: "corsair-rm750-power-supply",
  },
  {
    id: "part-3",
    name: "DDR4 RAM kit",
    category: "Memory",
    brandModel: "16GB DDR4-3200",
    purchaseCost: 55.0,
    condition: "Good",
    testingStatus: "Passed",
    currentStatus: "Assigned to Build",
    storageLocation: "Build station",
    assignedBuild: "Legacy Powerhouse",
    slug: "ddr4-ram-kit",
  },
  {
    id: "part-4",
    name: "SSD",
    category: "Storage",
    brandModel: "500GB NVMe SSD",
    purchaseCost: 40.0,
    condition: "Good",
    testingStatus: "Needs Testing",
    currentStatus: "Available",
    storageLocation: "Parts bin B",
    slug: "500gb-nvme-ssd",
  },
  {
    id: "part-5",
    name: "PC case",
    category: "Case",
    brandModel: "Montech XR Black",
    purchaseCost: 60.0,
    condition: "Good",
    testingStatus: "Passed",
    currentStatus: "Listed Separately",
    storageLocation: "Garage shelf A",
    slug: "montech-xr-black-case",
  },
  { id: "asset-3060ti", slug: "asus-rtx-3060-ti", name: "ASUS RTX 3060 Ti 8GB", category: "GPU", brandModel: "ASUS RTX 3060 Ti 8GB", purchaseCost: 0, condition: "Not entered", testingStatus: "Passed", currentStatus: "Assigned to Build", availability: "Unavailable", storageLocation: "Installed in Build", assignedBuild: "Blue Titan", assetHistory: [{ action: "Assigned to build", note: "Installed in Blue Titan." }] },
  { id: "asset-gtx1080", slug: "nvidia-gtx-1080", name: "NVIDIA GeForce GTX 1080", category: "GPU", brandModel: "NVIDIA GeForce GTX 1080", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Assigned to Build", availability: "Unavailable", storageLocation: "Installed in Build", assignedBuild: "Legacy Powerhouse", assetHistory: [{ action: "Assigned to build", note: "Installed in Legacy Powerhouse." }] },
  { id: "asset-1050ti", slug: "nvidia-gtx-1050-ti", name: "NVIDIA GeForce GTX 1050 Ti", category: "GPU", brandModel: "Not entered", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Available", availability: "Available", storageLocation: "Available Inventory" },
  { id: "asset-rx580", slug: "amd-radeon-rx-580", name: "AMD Radeon RX 580", category: "GPU", brandModel: "Not entered", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Available", availability: "Available", storageLocation: "Available Inventory" },
  { id: "asset-darkflash", slug: "darkflash-dn360d-aio", name: "darkFlash DN360D 360mm AIO Liquid Cooler", category: "CPU Cooler", brandModel: "360mm AIO Liquid Cooler with 2.1-inch LCD", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Available", availability: "Available", storageLocation: "Unknown", notes: "Socket compatibility and mounting hardware need verification." },
  { id: "asset-rise-mode", slug: "rise-mode-argb-air-cooler", name: "Winter Cooler Rise Mode ARGB Air Cooler", category: "CPU Cooler", brandModel: "ARGB Air Cooler", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Available", availability: "Available", storageLocation: "Unknown", notes: "Socket compatibility and mounting hardware need verification." },
  { id: "asset-evga-650", slug: "evga-650w-bronze-psu", name: "EVGA 650W 80+ Bronze PSU", category: "Power Supply", brandModel: "EVGA 650W 80+ Bronze", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Needs Parts", availability: "Restricted", storageLocation: "Unknown", notes: "Missing modular cables. Verify exact PSU model; never use random modular cables." },
  ...Array.from({ length: 6 }, (_, index) => ({ id: `asset-rs120-${index + 1}`, slug: `rs120-argb-fan-${index + 1}`, name: `RS120 ARGB 120mm PWM Fan ${index + 1}`, category: "Case Fan", brandModel: "RS120 ARGB 120mm PWM Fans, Revival Series", purchaseCost: 0, condition: "Not entered", testingStatus: "Unknown", currentStatus: "Available", availability: "Available" as const, storageLocation: "Unknown", notes: `Original pack grouping: ${index < 3 ? "Pack 1" : "Pack 2"}.` })),
];

export const seedListings: MarketplaceListing[] = [
  { id: "listing-blue-fb", buildId: "build-3", marketplace: "Facebook Marketplace", title: "Blue Titan", price: 999, status: "Active", lastUpdated: "2026-07-25", priceHistory: [{ price: 999, date: "2026-07-25", note: "Seed listing record" }] },
  { id: "listing-blue-ebay", buildId: "build-3", marketplace: "eBay", title: "Blue Titan", price: 1099, status: "Active", lastUpdated: "2026-07-25", priceHistory: [{ price: 1099, date: "2026-07-25", note: "Seed listing record" }] },
  { id: "listing-blue-mercari", buildId: "build-3", marketplace: "Mercari", title: "Blue Titan", status: "Needs Price Confirmation", lastUpdated: "2026-07-25", notes: "Mercari listing price needs confirmation. Enter the exact current listing price." },
];

export const deals: Deal[] = [
  {
    id: "deal-1",
    marketplace: "Facebook Marketplace",
    title: "RTX 4060 desktop bundle",
    listingPrice: 225.0,
    estimatedMarketValue: 280.0,
    estimatedFees: 16.0,
    estimatedShipping: 15.0,
    estimatedProfit: 24.0,
    riskLevel: "Medium",
    flipScore: 81,
    sellerRating: "4.7/5",
    category: "GPU",
    note: "Good value if the card is tested and fully functional.",
  },
  {
    id: "deal-2",
    marketplace: "eBay",
    title: "RTX 3060 Ti 8GB",
    listingPrice: 210.0,
    estimatedMarketValue: 260.0,
    estimatedFees: 19.0,
    estimatedShipping: 10.0,
    estimatedProfit: 21.0,
    riskLevel: "Medium",
    flipScore: 76,
    sellerRating: "4.6/5",
    category: "GPU",
    note: "Promising if the seller confirms the card works properly.",
  },
  {
    id: "deal-3",
    marketplace: "Mercari",
    title: "Ryzen 5 bundle with motherboard",
    listingPrice: 140.0,
    estimatedMarketValue: 180.0,
    estimatedFees: 12.0,
    estimatedShipping: 8.0,
    estimatedProfit: 20.0,
    riskLevel: "Low",
    flipScore: 88,
    sellerRating: "4.9/5",
    category: "CPU Bundle",
    note: "A useful bundle if the board and CPU pair well together.",
  },
  {
    id: "deal-4",
    marketplace: "Recently Discovered",
    title: "Compatible Legacy Powerhouse motherboard",
    listingPrice: 95.0,
    estimatedMarketValue: 125.0,
    estimatedFees: 8.0,
    estimatedShipping: 8.0,
    estimatedProfit: 14.0,
    riskLevel: "High",
    flipScore: 72,
    sellerRating: "4.3/5",
    category: "Motherboard",
    note: "Mock saved search for an LGA1151 board that fits the i7-7700K use case.",
  },
];

export const testingChecklist: TestingChecklistItem[] = [
  { id: "boot", label: "Boot test", done: true },
  { id: "bios", label: "BIOS check", done: true },
  { id: "cpu", label: "CPU stress test", done: true },
  { id: "gpu", label: "GPU stress test", done: false },
  { id: "ram", label: "RAM test", done: true },
  { id: "storage", label: "Storage health", done: false },
  { id: "temps", label: "Temperature check", done: false },
  { id: "activation", label: "Windows activation", done: true },
  { id: "drivers", label: "Driver installation", done: false },
  { id: "benchmark", label: "Benchmark results", done: false },
  { id: "cleaning", label: "Cleaning complete", done: true },
  { id: "cables", label: "Cable management complete", done: true },
  { id: "photos", label: "Photos complete", done: false },
  { id: "ready", label: "Ready to list", done: false },
];

export const aiMessages: AiMessage[] = [
  { id: "m1", role: "assistant", content: "Review Blue Titan pricing." },
  { id: "m2", role: "assistant", content: "Confirm where the RTX 3070 went." },
  { id: "m3", role: "assistant", content: "Add final sale data for Legacy Powerhouse." },
  { id: "m4", role: "assistant", content: "Enter loose-parts inventory." },
  { id: "m5", role: "assistant", content: "Complete testing before listing." },
];

export const tasks: TaskItem[] = [
  { id: "task-1", title: "Review Blue Titan pricing", relatedBuild: "Blue Titan", priority: "High", status: "Open", dueDate: "2026-07-26", completed: false, notes: "Check if the listing needs to be lowered." },
  { id: "task-2", title: "Add missing final sale data for Legacy Powerhouse", relatedBuild: "Legacy Powerhouse", priority: "High", status: "Blocked", dueDate: "2026-07-26", completed: false, notes: "Waiting for final sale outcome." },
  { id: "task-3", title: "Enter current loose-parts inventory", relatedBuild: "Inventory", priority: "Medium", status: "In Progress", dueDate: "2026-07-27", completed: false, notes: "Include the RTX 3070 and power supply." },
  { id: "task-4", title: "Confirm where the RTX 3070 from Build #1 went", relatedBuild: "i5-12600K + RTX 4060 Gaming PC", priority: "Medium", status: "Open", dueDate: "2026-07-27", completed: false, notes: "This is needed for accurate inventory records." },
  { id: "task-5", title: "Find missing part: Compatible Motherboard", buildId: "build-2", relatedBuild: "Legacy Powerhouse", priority: "High", status: "Blocked", dueDate: "2026-07-28", completed: false, notes: "Must support LGA1151 and DDR4." },
  { id: "task-6", title: "Run testing USB on active builds", relatedBuild: "Legacy Powerhouse", priority: "Medium", status: "Open", dueDate: "2026-07-29", completed: false, notes: "Use the mock testing checklist." },
  { id: "task-7", title: "Photograph current listing", relatedBuild: "Blue Titan", priority: "Medium", status: "Open", dueDate: "2026-07-29", completed: false, notes: "Capture main and cable-management photos." },
  { id: "task-8", title: "Prepare Mercari shipment when applicable", relatedBuild: "i5-12600K + RTX 4060 Gaming PC", priority: "Low", status: "Completed", dueDate: "2026-07-24", completed: true, notes: "Shipment prep is already marked done for the demo data." },
];

export const notifications: NotificationItem[] = [
  { id: "n1", title: "Legacy Powerhouse needs a compatible motherboard", description: "The build is blocked until the replacement board is found.", unread: true },
  { id: "n2", title: "Blue Titan pricing should be reviewed", description: "The listing has been up for several days and the price should be checked.", unread: true },
  { id: "n3", title: "RTX 3070 location is unconfirmed", description: "Inventory tracking still needs a location note.", unread: true },
  { id: "n4", title: "Two parts need testing", description: "The RTX 3070 and SSD are still marked as needing testing.", unread: false },
  { id: "n5", title: "Legacy Powerhouse is missing final sale data", description: "The sale outcome is still not recorded.", unread: false },
];

export const motherboardCompatibility = [
  {
    name: "Gigabyte Z270 Gaming K3",
    compatibilityScore: 100,
    summary: "Excellent match because it supports the i7-7700K, DDR4 memory, and has enough PCIe room for the GTX 1080.",
    notes: ["LGA1151", "Supports 7th-gen Intel", "DDR4 support", "PCIe x16 available", "I/O shield included"],
    status: "Compatible",
  },
  {
    name: "ASUS Prime H270-Plus",
    compatibilityScore: 95,
    summary: "Strong match, but it is missing the I/O shield in the mock listing.",
    notes: ["LGA1151", "Supports Kaby Lake", "DDR4 support", "PCIe x16 available", "Needs I/O shield"],
    status: "Compatible but missing I/O shield",
  },
  {
    name: "MSI B250M PRO-VDH",
    compatibilityScore: 70,
    summary: "May work, but it needs BIOS confirmation before the build is considered safe.",
    notes: ["LGA1151", "DDR4 support", "PCIe x16 available", "Requires BIOS check"],
    status: "Requires BIOS update",
  },
  {
    name: "ASRock H110M-HDV",
    compatibilityScore: 25,
    summary: "Wrong chipset class for this use case and likely not the right fit.",
    notes: ["Wrong chipset", "Limited PCIe support", "May not support the CPU well"],
    status: "Not compatible",
  },
];

export const plannedFeatures = [
  "AI Deal Score from 0 to 100",
  "Live marketplace scanning",
  "Price trends",
  "Profit trends by month",
  "Expense tracker",
  "Drag-and-drop photos",
  "Printable invoices and receipts",
  "Barcode labels",
  "QR labels",
  "Storage map",
  "ROI leaderboard",
  "Time spent per build",
  "Daily profit goals",
  "Weekly profit goals",
  "Progress streaks",
  "Price-drop reminders",
  "Build changelog",
  "Wishlist of parts",
  "Favorite saved searches",
  "Mobile quick actions",
  "Morning summary",
  "Evening summary",
  "Achievements",
  "What-if profit calculator",
  "AI negotiation assistant",
  "AI listing generator",
  "Customer database",
  "Team accounts",
  "Discord alerts",
  "Email alerts",
  "eBay API",
  "Best Buy API",
  "Amazon integration where permitted",
  "Mercari support",
  "Facebook Marketplace support only where permitted",
  "Supabase",
  "Vercel deployment",
  "Real AI provider",
  "OpenAI",
  "Claude",
  "Gemini",
  "Marketplace fee engine",
  "Shipping estimator",
  "Tax export",
  "Inventory import",
  "Build templates",
  "Smart recommendations",
  "Price prediction",
  "Time-to-sell prediction",
];

export const settingsDefaults = {
  profileName: "Tristen",
  preferredCurrency: "USD",
  defaultMarketplace: "Mercari",
  discordAlerts: true,
  emailAlerts: true,
  darkMode: true,
  dealAlertFrequency: "Daily",
  minimumTargetProfit: 100,
  preferredParts: ["RTX 4060", "RTX 3060 Ti", "Ryzen 5", "white cases"],
};

const dealSeedDate = "2026-07-25T12:00:00.000Z";
const defaultSearchRows: Array<[string, string, string, string?, string?]> = [
  ["RTX 4060 Ti below target", "GPU", "RTX 4060 Ti", "NVIDIA", "RTX 40-series"], ["RTX 4060 below target", "GPU", "RTX 4060", "NVIDIA", "RTX 40-series"], ["RTX 3070 below target", "GPU", "RTX 3070", "NVIDIA", "RTX 30-series"], ["RTX 3060 Ti below target", "GPU", "RTX 3060 Ti", "NVIDIA", "RTX 30-series"], ["AM4 gaming PC opportunities", "Complete PC", "AM4 gaming PC", undefined, undefined], ["AM5 gaming PC opportunities", "Complete PC", "AM5 gaming PC", undefined, undefined], ["Legacy Powerhouse motherboard", "Motherboard", "LGA1151 motherboard", undefined, undefined], ["Blue Titan recreation parts", "GPU", "Blue Titan GPU", "NVIDIA", "RTX 40-series"], ["Used Ryzen 5 bundles", "CPU Bundle", "Ryzen 5 bundle", undefined, undefined], ["Used RTX 30-series GPUs", "GPU", "RTX 30-series", "NVIDIA", "RTX 30-series"], ["Used RTX 40-series GPUs", "GPU", "RTX 40-series", "NVIDIA", "RTX 40-series"],
];
export const savedDealSearches: SavedDealSearch[] = defaultSearchRows.map(([name, category, terms, gpuManufacturer, gpuGeneration], index) => ({ id: `saved-search-${index + 1}`, name, category, terms, marketplace: "All", condition: "Used", returnsRequired: false, fulfillment: "Any", gpuManufacturer, gpuGeneration, excludeLaptopGpu: category === "GPU", excludeAccessories: category === "GPU", allowForParts: false, requireAllRules: true, riskThreshold: "High", notificationEnabled: true, active: true, lastChecked: dealSeedDate, lastResultCount: 0, createdAt: dealSeedDate, updatedAt: dealSeedDate }));

export const dealOpportunities: DealOpportunity[] = [
  { id: "opportunity-legacy-board", title: "Gigabyte Z270 Gaming K3 LGA1151 DDR4 motherboard", marketplace: "Recently Discovered", listingType: "Part", category: "Motherboard", sourceType: "Mock", askingPrice: 80, condition: "Used", sellerName: "Sample seller", sellerRating: 4.9, returnPolicy: "Returns accepted", offersEnabled: true, location: "Local listing", dateFound: dealSeedDate, lastChecked: dealSeedDate, compatibleBuildIds: ["build-2"], missingPartCompleted: "Legacy Powerhouse", compatibility: "Compatible", compatibilityExplanation: "Sample candidate supports LGA1151, 7th-gen Intel, and DDR4. Confirm listing details before buying.", testingStatus: "Untested" },
  { id: "opportunity-rtx4060", title: "GeForce RTX4060TI graphics card", marketplace: "Recently Discovered", listingType: "Part", category: "GPU", sourceType: "Mock", askingPrice: 260, shipping: 12, condition: "Used", sellerRating: 4.8, returnPolicy: "Returns accepted", offersEnabled: true, dateFound: dealSeedDate, lastChecked: dealSeedDate, estimatedResaleValue: 320, estimatedSellingFees: 32, estimatedSellerShipping: 18, compatibility: "Unknown", testingStatus: "Untested" },
  { id: "opportunity-am4", title: "Ryzen 5 AM4 gaming PC bundle", marketplace: "Recently Discovered", listingType: "Complete PC", category: "Complete PC", sourceType: "Mock", askingPrice: 300, travelCost: 15, condition: "Used", sellerRating: 4.6, returnPolicy: "No returns", offersEnabled: true, location: "Local listing", dateFound: dealSeedDate, lastChecked: dealSeedDate, compatibility: "Compatible with Warning", compatibilityExplanation: "AMD AM4 is aligned with your stated preference, but components need verification.", testingStatus: "Untested" },
];
