import "server-only";
import { ebayAdapter } from "@/lib/marketplaces/ebay";
import type { MarketplaceProvider, MarketplaceProviderDefinition, MarketplaceProviderId } from "@/lib/marketplaces/types";
function unavailableProvider(definition: MarketplaceProviderDefinition): MarketplaceProvider { return { definition, status: () => ({ configured: false, reason: definition.unavailableReason }), search: async () => { throw new Error(definition.unavailableReason ?? `${definition.label} is not available.`); } }; }
const providers: Record<MarketplaceProviderId, MarketplaceProvider> = { ebay: ebayAdapter, amazon: unavailableProvider({ id: "amazon", label: "Amazon", liveSearch: false, configurationRequired: true, unavailableReason: "Amazon monitoring needs approved official API credentials and an allowed product-data use case before it can be enabled." }), jawa: unavailableProvider({ id: "jawa", label: "Jawa", liveSearch: false, configurationRequired: false, unavailableReason: "Jawa does not currently provide a public listing-search API for this integration." }), newegg: unavailableProvider({ id: "newegg", label: "Newegg", liveSearch: false, configurationRequired: true, unavailableReason: "Newegg monitoring needs an approved official integration before it can be enabled." }), "best-buy": unavailableProvider({ id: "best-buy", label: "Best Buy", liveSearch: false, configurationRequired: true, unavailableReason: "Best Buy monitoring needs an approved official integration before it can be enabled." }), craigslist: unavailableProvider({ id: "craigslist", label: "Craigslist", liveSearch: false, configurationRequired: false, unavailableReason: "Craigslist does not provide an approved public listing-search API for this integration." }), "facebook-marketplace": unavailableProvider({ id: "facebook-marketplace", label: "Facebook Marketplace", liveSearch: false, configurationRequired: false, unavailableReason: "Facebook Marketplace does not provide a general public listing-search API for this integration." }) };
export function getMarketplaceProvider(id: string) { return providers[id as MarketplaceProviderId]; }
export function listMarketplaceProviders() { return Object.values(providers).map((provider) => ({ ...provider.definition, ...provider.status() })); }
export { ebayAdapter };
export type { MarketplaceProviderId, MarketplaceSearchRequest, NormalizedListing, MarketplaceSearchPage } from "@/lib/marketplaces/types";
